// AUTH actions
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const LOGOUT = 'LOGOUT';
export const UPDATE_USER = 'UPDATE_USER';
export const FORGOT = 'FORGOT';
export const RESET = 'RESET';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const PASS_CHANGE = 'PASS_CHANGE';

// Collection actions
export const ADD_COLLECTION = 'ADD_COLLECTION';
export const DELETE_COLLECTION = 'DELETE_COLLECTION';
export const FORK_COLLECTION = 'FORK_COLLECTION';
export const UPDATE_COLLECTION = 'UPDATE_COLLECTION';
export const GET_COLLECTIONS = 'GET_COLLECTIONS';
export const GET_COLLECTION = 'GET_COLLECTION';
export const COLLECTION_ERROR = 'COLLECTION_ERROR';
export const CLEAR_COLLECTION_ERROR = 'CLEAR_COLLECTION_ERROR';
